"""Add upload_time column

Revision ID: 85f41db54ff9
Revises: 
Create Date: 2025-06-27 11:39:03.187198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f41db54ff9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.execute("ALTER TABLE device ALTER COLUMN device_type TYPE INTEGER USING device_type::integer")

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.Date(), nullable=False))

    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'operator', ['who_created'], ['operator_id'])
        batch_op.create_foreign_key(None, 'operator', ['who_responsible'], ['operator_id'])
        batch_op.drop_column('location')

    with op.batch_alter_table('experiment_device', schema=None) as batch_op:
        batch_op.drop_column('parametres')

    with op.batch_alter_table('log_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_time', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_file', schema=None) as batch_op:
        batch_op.drop_column('upload_time')

    with op.batch_alter_table('experiment_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parametres', sa.VARCHAR(length=512), autoincrement=False, nullable=False))

    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_time')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('device_type',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
